apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fpjh2j1w0-java-springboot
  janus-idp.io/tekton: fpjh2j1w0-java-springboot
  backstage.io/kubernetes-id: fpjh2j1w0-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fpjh2j1w0-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
